spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/CyclicApp?useUnicode=true&characterEncoding=utf-8
    username: root
    password: qwer1234

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml