spring:
  datasource:
    url: jdbc:mysql://root:KNLsTRIZzbtuVDFw1crV@containers-us-west-40.railway.app:7919/railway
    username: root
    password: KNLsTRIZzbtuVDFw1crV

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
