spring:
  datasource:
    url: jdbc:mysql://root:KNLsTRIZzbtuVDFw1crV@containers-us-west-40.railway.app:7919/railway
    username: root
    password: KNLsTRIZzbtuVDFw1crV

resources:
  static-locations: classpath:/static/
  static-cache-period: 3600
  template-locations: classpath:/templates/
  cache-period: 3600

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  

